FROM sonarqube:7.1

ADD https://github.com/SonarQubeCommunity/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-1.21/sonar-l10n-zh-plugin-1.21.jar /opt/sonarqube/extensions/plugins/
ADD https://repox.sonarsource.com/sonarsource/org/sonarsource/xml/sonar-xml-plugin/1.5.1.1452/sonar-xml-plugin-1.5.1.1452.jar /opt/sonarqube/extensions/plugins/
ADD https://binaries.sonarsource.com/Distribution/sonar-java-plugin/sonar-java-plugin-5.6.0.15032.jar /opt/sonarqube/extensions/plugins/