version: '3'
services:
    server:
        image: daocloud.io/buxiaomo/ngrok:latest
        environment:
            - NGROK_DOMAIN=example.com
        networks:
            ngrok:
        volumes:
            - /etc/ngrok:/etc/ngrok
            - /var/run/docker.sock:/var/run/docker.sock:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.labels.ngrok == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

networks:
    ngrok:
        external:
            name: "host"