name: PHP Images

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/php.yml'
      - 'php-ext'
  schedule:
    - cron: '00 18 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.DOCKERIO_USERNAME }}
        password: ${{ secrets.DOCKERIO_PASSWORD }}

    - name: Build images
      run: |
        docker build php-ext/7.2 -t buxiaomo/php:7.2.8-fpm-alpine3.7.ext
        docker push buxiaomo/php:7.2.8-fpm-alpine3.7.ext
